services:
  - type: web
    name: metaqi-academy-web
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run build:web
    staticPublishPath: dist
    envVars:
      - key: EXPO_PUBLIC_BACKEND_URL
        value: https://metaqi-academy.onrender.com
      - key: EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID
        value: 565707207903-3hsai2h4k39668uen1lsr2vs1avlivo7.apps.googleusercontent.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
